POST http://localhost:3000/memories/
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="image"; filename="esn.png"
Content-Type: image/jpeg

< ../esn.png
--boundary--
