POST http://localhost:3000/memories/
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="image"; filename="frase.jpg"
Content-Type: image/jpeg

< ../frase.jpg
--boundary
Content-Disposition: form-data; name="title"

testing
--boundary
Content-Disposition: form-data; name="description"

descrição 25
--boundary--

###
GET http://localhost:3000/memories/
###
DELETE  http://localhost:3000/memories/66f2f6e671467d43dcd06b21

###
PATCH http://localhost:3000/memories/66f445bad639ca76683b3850
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="title"

Atualizado titulo
--boundary
Content-Disposition: form-data; name="description"

Atualizado descrição
--boundary
Content-Disposition: form-data; name="image"; filename="esn.png"
Content-Type: image/png

< ../esn.png
--boundary--